export const homeQuotes = [
  "A quiet page can hold the loudest secret in the house.",
  "Every locked drawer begins as a sentence waiting for its key.",
  "In warm ink and candlelight, even silence learns to confess.",
  "The truth often arrives softly, dressed as a story.",
  "A story is a lantern carried through an unfamiliar room.",
  "Some mysteries do not hide in shadows; they wait between lines.",
  "Ink remembers what the tongue refuses to say.",
  "The oldest secrets are patient enough to become literature.",
  "Every chapter opens a door the house forgot it had.",
  "A good sentence leaves footprints in the mind.",
  "The page is never empty; it is only holding its breath.",
  "Stories are keys made from memory and doubt.",
  "A candle does not defeat darkness; it teaches it to speak.",
  "The finest clues are often written in ordinary ink.",
  "Every reader becomes a witness once the first page turns.",
  "A hidden truth is only a story waiting for courage.",
  "The margin is where quiet thoughts learn their names.",
  "Some endings arrive disguised as beginnings.",
  "A room grows larger when a story enters it.",
  "The heart keeps better archives than any library.",
  "A secret told beautifully becomes a door, not a wound.",
  "Every old book carries the dust of someone's midnight.",
  "The softest voices often leave the deepest marks.",
  "A mystery begins when certainty loses its way.",
  "Words are small lamps along the corridor of memory.",
  "The past is never silent; it merely changes its handwriting.",
  "Every page asks the reader to lean a little closer.",
  "A tale worth keeping always has one shadow left.",
  "Ink turns fear into something the hand can hold.",
  "The best stories do not answer; they awaken.",
  "A name written once can echo for years.",
  "Every secret has a weather of its own.",
  "The door in the story opens inward first.",
  "A writer gathers darkness to show where the light begins.",
  "The quietest clue is often the most faithful.",
  "A page can become a mirror if read at the right hour.",
  "The night keeps no diary, so writers must.",
  "A sentence can be a candle, a key, or a confession.",
  "Every mystery asks for patience before revelation.",
  "Old paper knows how to make silence feel alive.",
  "The reader enters alone and leaves with witnesses.",
  "Some truths need fiction before they can be faced.",
  "A story is a sealed letter opened by strangers.",
  "The most dangerous rooms are made of memory.",
  "Every tale begins with someone listening closely.",
  "A secret loses its terror when given a beautiful shape.",
  "The ink is dark because the heart is deep.",
  "Every unread page is a door with no handle yet.",
  "A story can warm the room and unsettle it at once.",
  "The best mysteries leave a little candle burning.",
  "Every shadow in a story belongs to a light nearby.",
  "A writer is a keeper of rooms no one else can enter.",
  "The page forgives what the world interrupts.",
  "A forgotten letter can outlive an entire house.",
  "Stories teach silence how to leave evidence.",
  "The heart reads before the eyes understand.",
  "Every library is built from rescued whispers.",
  "A clue is a small truth wearing a plain coat.",
  "The past knocks softly, then waits in the prose.",
  "A story is the art of making absence visible.",
  "Some pages smell of rain, wax, and unfinished courage.",
  "The bravest confession may arrive as fiction.",
  "Every chapter is a room with a secret window.",
  "A sentence can cross years without losing its pulse.",
  "The reader's lamp completes what the writer began.",
  "Stories are the maps we draw after getting lost.",
  "A mystery is only wonder wearing a darker coat.",
  "The oldest houses remember in paragraphs.",
  "Every quiet ending leaves one question awake.",
  "The page turns, and the room changes its mind.",
  "A secret kept too long begins to write itself.",
  "Ink is how memory learns to stay.",
  "The finest stories sound like someone telling the truth at last.",
  "A candlelit page can make the whole world listen.",
  "Every locked heart has a library somewhere inside.",
  "The mystery deepens when the answer feels human.",
  "A story begins where explanation grows tired.",
  "Some doors open only for patient readers.",
  "The truth is rarely loud; it is usually legible.",
  "Every sentence carries a little weather from the soul.",
  "A book is a house where strangers become witnesses.",
  "The unanswered question keeps the candle alive.",
  "A page can hold both the wound and the remedy.",
  "Every hidden case begins with someone noticing.",
  "The best stories leave fingerprints on silence.",
  "A secret is safest until the ink finds it.",
  "The reader is the final room in every story.",
  "Old stories do not fade; they gather warmth.",
  "A good mystery makes the ordinary shimmer.",
  "The page is a window with curtains of ink.",
  "Every writer leaves a lantern for the next lost soul.",
  "A story is proof that silence was never empty.",
  "The heart hides its evidence in metaphor.",
  "Some truths need a softer light to be seen.",
  "Every book is a conversation with the unseen.",
  "The final line should feel like a door closing gently.",
  "A quiet clue can overturn the whole room.",
  "Stories begin as sparks and end as ashes we keep.",
  "The ink knows the way through the dark.",
  "Every reader brings a different candle to the same page.",
];

export function getRandomHomeQuoteIndex() {
  return Math.floor(Math.random() * homeQuotes.length);
}
