import { Router } from "express";

import { authRouter } from "./auth.js";
import { postsRouter } from "./posts.js";
import { commentsRouter } from "./comments.js";
import { usersRouter } from "./users.js";
import { adminRouter } from "./admin.js";
import { seriesRouter } from "./series.js";
import { aiRouter } from "./ai.js";
import { revisionsRouter } from "./revisions.js";
import { tagsRouter } from "./tags.js";
import { notificationsRouter } from "./notifications.js";
import { reportsRouter } from "./reports.js";
import { challengesRouter } from "./challenges.js";
import { groupsRouter } from "./groups.js";
import { qaRouter } from "./qa.js";
import { continuationsRouter } from "./continuations.js";
import { kudosRouter } from "./kudos.js";
import { leaderboardRouter } from "./leaderboard.js";
import { messagesRouter } from "./messages.js";
import { pollsRouter } from "./polls.js";
import { exportRouter } from "./export.js";
import { questsRouter } from "./quests.js";
import { analyticsRouter } from "./analytics.js";

export const router = Router();

router.use("/auth", authRouter);
router.use("/posts", postsRouter);
router.use("/comments", commentsRouter);
router.use("/users", usersRouter);
router.use("/admin", adminRouter);
router.use("/series", seriesRouter);
router.use(tagsRouter);
router.use("/notifications", notificationsRouter);
router.use("/reports", reportsRouter);
router.use("/challenges", challengesRouter);
router.use("/groups", groupsRouter);
router.use(qaRouter);
router.use(continuationsRouter);
router.use(kudosRouter);
router.use("/leaderboard", leaderboardRouter);
router.use(messagesRouter);
router.use(pollsRouter);
router.use("/quests", questsRouter);
router.use("/analytics", analyticsRouter);
router.use(aiRouter);
router.use(revisionsRouter);
router.use(exportRouter);
